/* Automatically generated by './build/bin/build-entry.js' */


import Button from '../packages/button/index.js';
import ButtonGroup from '../packages/button-group/index.js';


const components = [
  Button,
  ButtonGroup,
];

const install = function(Vue, opts = {}) {
  locale.use(opts.locale);

  components.forEach(component => {
    Vue.component(component.name, component);
  });

  Vue.use(InfiniteScroll);
  Vue.use(Loading.directive);

  Vue.prototype.$ELEMENT = {
    size: opts.size || '',
    zIndex: opts.zIndex || 2000
  };



};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '2.12.0',
  Button,
  ButtonGroup
};
